name: "Feature Request"
description: "Suggest an idea for this project, Choose this option when you would like to request afeature to an existing/new resource, data source, or the provider itself."
title: "[FEATURE REQUEST]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for opening an feature request!

        This form is intended as a way to request feature for existing/new resources, data sources, or the provider itself. This may include requests such as adding additional arguments or attributes enabled by upstream API changes, additional validation for arguments, adding new resource or data-source etc.

        If the absense of the requested feature is causing unexpected behavior in the provider, the "Report a Bug" form should be used.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the new feature/improvement briefly below.
      placeholder: >-
        I am trying to do X with the collection and I think that implementing a feature Y would be very helpful for me
        and every other user of `netscaler.adc` because of Z. OR 
        [New Resource]: - for new resource requests 
        [New Data Source]: - for new data source requests]
    validations:
      required: true

  - type: textarea
    id: affected
    attributes:
      label: Affected Resource(s) and/or Data Source(s)
      placeholder: "* citrixadc_xxx_yyy"
    validations:
      required: false

  - type: textarea
    id: cli_command
    attributes:
      label: Equivalent NetScaler CLI Command
      description: Please provide the equivalent NetScaler CLI command for the affected resource(s)/new resource.
      placeholder: "NetScaler CLI command"
    validations:
      required: true

  - type: textarea
    id: tf_config
    attributes:
      label: Potential Terraform Configuration
      description: |
        If this request was implemented, what might the Terraform configuration look like? A best guess is helpful, even if you're unsure of exactly what the end result will look like. This helps maintainers and the community better understand how you (someone who is in need of this feature) envisions it.

        **Note:** This field will render in HCL, so there is no need to add a [code fence](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).
      render: terraform
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Where possible, please supply links to vendor documentation, other GitHub issues (open or closed) or pull requests that give additional context.
        Link to the NetScaler ADC Nitro API documentation, if applicable.

        [Information about referencing Github Issues](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests)
    validations:
      required: false
